CREATE DATABASE mydatabase;
use mydatabase;
CREATE USER 'pythonuser'@'localhost' IDENTIFIED BY 'mypassword';

GRANT ALL PRIVILEGES ON mydatabase.* TO 'pythonuser'@'localhost';

FLUSH PRIVILEGES;

select * from my_table Limit 5;

#Q1 What is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount)as total_revenue
from my_table
group by gender;

#q2.Which customer used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from my_table 
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from my_table)

#Q3.Which are the top 5 Products with the highest average review rating?
select  item_purchased, Round(Avg(review_rating),2) as Average_review_rating
from my_table
group by item_purchased
order by Average_review_rating desc
limit 5;

#Q4.Compare the average purchase amount between the expressband standard shipping ?
select shipping_type,
round(avg(purchase_amount),2)
from my_table
where shipping_type in ('Express','Standard')
group by shipping_type;

#Q4.Do Subscribed customers spend more ? Compare average spend and total revenue between subscribers and non-subscribers?
select subscription_status,
count(customer_id),
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_revenue
from my_table
group by subscription_status 
order by total_revenue and average_spend desc;

#Q6 Which 5 Products have the highest percentage of purchases with discounts applied ?
select item_purchased,
round (100* sum(case when discount_applied='Yes' Then  1 else 0 end)/count(*),2) as discount_rate
from my_table
group by item_purchased
order by discount_rate desc
limit 5;

#Q7.Segment Customers into New, Returning,loyal based on their total number of previous purchases  and show the count of each segment ?
with customer_type as(
select customer_id,previous_purchases,
case 
    when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
    End as customer_segment
from my_table
)
select customer_segment, count(*) as Number_of_customers
from customer_type
group by customer_segment

#8.What are 3 most purchased products within each category ?
with item_counts as (
select Category,item_purchased,
count(customer_id) as total_orders,
Row_Number() over (Partition by Category order by count(customer_id)  desc) as  item_rank
from my_table
group by Category,item_purchased
)
select item_rank,total_orders,Category,item_purchased
from  item_counts
where item_rank<=3;
#Q9.Are Subscribers who are repreat buyers (more than 5 recent purchase) also likely to subscribe ?
select subscription_status,
count(customer_id) as repeat_buyers
from my_table
where previous_purchases>5
group by subscription_status
order by repeat_buyers desc ;

#Q10.What is the revenue contribution of each group ?
select age_group,
sum(purchase_amount) as revenue_contribution
from my_table
group by age_group







